### ISSUE TITLE
Broken streams again

### ISSUE THREAD

**Issue by mhartington** [isaacs/minipass#9] opened 2019-09-23 20:28 UTC
Seems the same issue from https://github.com/isaacs/minipass/issues/8 is back again. 

Between 2.8.2 and 2.8.3, we're seeing streams would stop being processed by tar, with minpass being the cause. Similar comment was made in #8

>Our issue was that tar 4.4.10 would apparently stop processing a stream, leaving the Node.js event loop empty and allowing the process to exit.

**Comment by fengmk2** [comment] 2019-09-24 01:28
Same here, minipass@>=2.8.2 is broken.

**Comment by j8hs** [comment] 2019-09-24 07:08
Downgrading minipass also doesn't fix the issue for me.

**Comment by isaacs** [comment] 2019-09-24 07:54
It's definitely not the same problem as #8.  I've tracked down the root cause, will revert the change that's breaking tar.

Need to figure out another way to handle tee-piping in the presence of already buffered data, I guess.

**Comment by isaacs** [comment] 2019-09-24 07:58
Pushed a 2.8.5 that makes minipass play nice with node-tar again.

The unfortunate part is that it means it _doesn't_ play nice with minipass-fetch, which is what prompted this change in the first place.  But way fewer people use that, so it's lower priority.

**Comment by j8hs** [comment] 2019-09-24 08:05
Issue is fixed with minipass@2.8.5.
Happy to see this again, thanks isaac!
![fixed](https://user-images.githubusercontent.com/55733940/65493235-bf81a380-deb2-11e9-89c1-bc6310ea2276.JPG)

**Comment by lovell** [comment] 2019-09-24 09:23
@isaacs Thank you for both addressing this problem so quickly and your continued maintenance of this module.

**Comment by isaacs** [comment] 2019-09-24 16:31
No problem, sorry for the hiccup :)

I updated the docs to explain how to do tee streams safely without losing data.  I don't think there's a way to make this work properly to get data to both places:

```js
src.write('foo')
src.pause()
src.pipe(d1)
src.pipe(d2)
src.resume()
```

So you just have to do this:

```js
src.write('foo')
const t = new Minipass()
t.pipe(d1)
t.pipe(d2)
src.pipe(t)
```

In any event, the overhead of an additional object is pretty minimal, compared with the overhead of the bookkeeping and heuristics to determine whether we should resume on pipe() or not.

**Closed by isaacs** 2019-09-24 16:31 UTC
